<a href="https://colab.research.google.com/github/niharika3632/Deep-Learning/blob/main/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("This notebook teaches the basics of pyotrch")

This notebook teaches the basics of pyotrch


**Tensor**

Tensor is a datastructure in which the input and output of neural network is encoded.

*   It is very similar to the numpy's ndarrays except it can run on the GPUs.
*   It eliminates the need to copy data.
*   It is optimized for automatic differentiation.


In [ ]:
#Importing the modules

runtime

In [3]:
for i in range(1, 1000000000):
  continue

KeyboardInterrupt: 

In [6]:
import torch
import numpy as np

**Initializing the Tensors**

There are various ways to create tensors
1. from data to tensors
2. from numpy array
3. from another tensor to retain the shape of the tensor
4. creating the tensor with the shape

In [2]:
data = [1,2,3]

x_data = torch.tensor(data)
x_data

tensor([1, 2, 3])

In [2]:
data = [[1,2,3],[5,6,7]]

x_data = torch.tensor(data)
x_data

tensor([[1, 2, 3],
        [5, 6, 7]])

In [4]:
np_array = np.array(data)
np_array

array([[1, 2, 3],
       [5, 6, 7]])

In [5]:
np_to_tensor = torch.from_numpy(np_array)
np_to_tensor

tensor([[1, 2, 3],
        [5, 6, 7]])

ones_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) -> Tensor

Returns a tensor filled with the scalar value 1, with the same size as
input. torch.ones_like(input) is equivalent to
torch.ones(input.size(), dtype=input.dtype, layout=input.layout, device=input.device).

Args:
    input (Tensor): the size of input will determine size of the output tensor.

Keyword arguments:
   1.  dtype (torch.dtype, optional): the desired data type of returned Tensor.
        Default: if None, defaults to the dtype of input.
   2.  layout (torch.layout, optional): the desired layout of returned tensor.
        Default: if None, defaults to the layout of input.
   3.  device (torch.device, optional): the desired device of returned tensor.
        Default: if None, defaults to the device of input.
   4.  requires_grad (bool, optional): If autograd should record operations on the
        returned tensor. Default: False.
   5.  memory_format (torch.memory_format, optional): the desired memory format of
        returned Tensor. Default: torch.preserve_format.

In [7]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1, 1],
        [1, 1, 1]])

In [10]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.9427, 0.9977, 0.0575],
        [0.3875, 0.2721, 0.2819]])

dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.

rand_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) -> Tensor

Returns a tensor with the same size as input that is filled with
random numbers from a uniform distribution on the interval [0, 1).
torch.rand_like(input) is equivalent to
torch.rand(input.size(), dtype=input.dtype, layout=input.layout, device=input.device).

Args:
 input (Tensor): the size of input will determine size of the output tensor.

Keyword args:

    1. dtype (torch.dtype, optional): the desired data type of returned Tensor.
        Default: if None, defaults to the dtype of input.
    2. layout (torch.layout, optional): the desired layout of returned tensor.
        Default: if None, defaults to the layout of input.
    3. device (torch.device, optional): the desired device of returned tensor.
        Default: if None, defaults to the device of input.
    4. requires_grad (bool, optional): If autograd should record operations on the
        returned tensor. Default: False.
    5. memory_format (torch.memory_format, optional): the desired memory format of
        returned Tensor. Default: torch.preserve_format.

In [18]:
x_rand = torch.rand_like(x_data, dtype=torch.complex32)
x_rand

<ipython-input-18-5e276f95eb5c>:1: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at /pytorch/aten/src/ATen/EmptyTensor.cpp:50.)
  x_rand = torch.rand_like(x_data, dtype=torch.complex32)


tensor([[0.0239+0.5430j, 0.8618+0.0767j, 0.2192+0.8188j],
        [0.1167+0.1836j, 0.4048+0.7476j, 0.4971+0.8066j]],
       dtype=torch.complex32)

In [25]:
x_zeros = torch.zeros_like(x_data)
x_zeros

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
rows = 2
cols = 4

shape = (rows, cols)

print("zeros tensor with shape 2 x 4")
x_ones = torch.ones(shape)
x_ones

tensor with shape 2 x 4


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
rows = 2
cols = 4

shape = (rows, cols)

print("tensor with shape 2 x 4")
x_ones = torch.rand(shape)
x_ones

tensor with shape 2 x 4


tensor([[0.5056, 0.5901, 0.2360, 0.2657],
        [0.7014, 0.3921, 0.9938, 0.3814]])

In [36]:
tensor_x = torch.rand(shape, dtype=torch.float16)
tensor_x

tensor([[0.1069, 0.2910, 0.2949, 0.3301],
        [0.4478, 0.9004, 0.3501, 0.1992]], dtype=torch.float16)

In [37]:
tensor_x.shape

torch.Size([2, 4])

In [40]:
tensor_x.dtype

torch.float16

In [41]:
tensor_x.device

device(type='cpu')

In [44]:
print(tensor_x.grad)

None


requires_grad_(requires_grad=True) -> Tensor

Change if autograd should record operations on this tensor: sets this tensor's
requires_grad attribute in-place. Returns this tensor.

requires_grad_'s main use case is to tell autograd to begin recording
operations on a Tensor tensor. If tensor has requires_grad=False
(because it was obtained through a DataLoader, or required preprocessing or
initialization), tensor.requires_grad_() makes it so that autograd will
begin to record operations on tensor.



In [50]:
tensor_x.requires_grad_(False)

tensor([[0.1069, 0.2910, 0.2949, 0.3301],
        [0.4478, 0.9004, 0.3501, 0.1992]], dtype=torch.float16)

In [51]:
tensor_x

tensor([[0.1069, 0.2910, 0.2949, 0.3301],
        [0.4478, 0.9004, 0.3501, 0.1992]], dtype=torch.float16)